### ISSUE TITLE
Does't work with Remote Development extension

### ISSUE THREAD

**Issue by rusnasonov** [rusnasonov/vscode-yandex-tracker#1]
1. Install [VSCode Insider](https://code.visualstudio.com/insiders/)
2. Install [Remote Development extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.vscode-remote-extensionpack)
3. Connect to remote host
4. Open Tracker Panel, wait while issues load.
5. Open Issue — WebView open, but issue content not loaded.

**Comment by perseus-me** [comment]
work on new vscode version (1.37)
